spring.application.name=petfinder
spring.data.mongodb.uri=mongodb://localhost:27017/petdb
server.port=8080
spring.data.mongodb.database=petdb
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
thedogapi.key=${THE_DOG_API_KEY:live_ZpN4I5R9bPq7gW0kL3m8nT2uV9xY1jA4B7cD0eF6hG3iK5lM}

file.upload-dir=./uploads/
app.base-url=http://localhost:8080
